(setq mac-pass-command-to-system nil)
(setq ns-alternate-modifier (quote none))
(setq ns-command-modifier (quote meta))
(setenv "PATH" (concat (getenv "PATH") ":/sw/bin"))
(setq exec-path (append exec-path '("/sw/bin")))