(set-background-color "gray12")
(set-foreground-color "AntiqueWhite3")
(set-cursor-color "AntiqueWhite3")
(set-face-background 'hl-line "gray11")
(set-face-background 'region "#3d3d3d")
(set-face-foreground 'region "#AntiqueWhite2")
(set-face-background 'show-paren-match "OliveDrab")

(set-face-foreground 'font-lock-keyword-face "#949c8b")
(set-face-foreground 'font-lock-constant-face "#6d9cbe")
(set-face-foreground 'font-lock-type-face "#a5c261")
(set-face-foreground 'font-lock-string-face "darkkhaki")
(set-face-foreground 'font-lock-comment-face "#444")

(provide 'my-colours)